config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :events do
    member do
      get 'select'
      get 'view'
    end
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :user, uniqueness: { scope: :event }
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :user_availabilities, dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :users, through: :attendances

  validates :title, presence: true
  validates :location, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :start_time_is_before_end_time

  private

  def start_time_is_before_end_time
    errors.add(:start_time, 'must take place before ending time') if (start_time <=> end_time) == 1
  end
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  include BCrypt

  has_many :user_availabilities, dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :events, through: :attendances

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validate :email_must_be_proper

  def password
    @password ||= Password.new(password_hash) if password_hash
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end

  private

  def email_must_be_proper
    errors.add(:email, "must have an '@' and a '.'") unless email.nil? || email.include?('@') && email.include?('.')
  end
end

app/models/user_availability.rb
class UserAvailability < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validate :slot_time_is_between_event_time

  private

  def slot_time_is_between_event_time
    errors.add(:slot_time, 'must take place during event') if (slot_time <=> event.start_time) == -1 || (slot_time <=> event.end_time) >= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method def logged_in?
    session[:user_id]
  end

  helper_method def current_user
    @current_user ||= User.find(session[:user_id]) if logged_in?
  end

  def authenticate_user
    redirect_to root_path unless logged_in?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :select, :view]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        add_friends
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        reformat
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def select
  end

  def view
  end

  private

  def reformat
    format.html { render :new }
    format.json { render json: @event.errors, status: :unprocessable_entity }
  end

  def add_friends
    current_user.events << @event
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:title, :location, :start_time, :end_time, :sunday, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.password == params[:password]
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    redirect_to root_path unless @user == current_user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user == current_user && @user.update(user_params)
        session[:user_id] = @user.id
        format.html { redirect_to edit_user_path(current_user), notice: 'User was successfully updated.' }
        format.json { render :edit, status: :ok, location: edit_user_path(current_user) }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy if @user == current_user
    respond_to do |format|
      format.html { redirect_to events_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_event
    if params[:event_id].present?
      @event = Event.find(params[:event_id])
      @user.events << @event unless @student.events.include?(@event)
    end
    redirect_to events_path
  end

  def delete_event
    @user.attendances.find(params[:event_id]).delete
    redirect_to events_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :event_title, class: 'form-control' %>
  </div>

  <br>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :event_location, class: 'form-control' %>
  </div>

  <br>


  <%= form.label 'Select all your preferred weekdays:' %>
  <table>
    <tbody>
      <tr>
        <td class="text-center">
          <div class="field">
          <%= form.label 'Sunday'%>
          <br>
          <%= form.check_box :sunday, id: :event_sunday %>
        </div>
        </td>
        <td class="text-center">
          <div class="field">
          <%= form.label 'Monday' %>
          <br>
          <%= form.check_box :monday, id: :event_monday %>
        </div>
        </td>
        <td class="text-center">
          <div class="field">
          <%= form.label 'Tuesday' %>
          <br>
          <%= form.check_box :tuesday, id: :event_tuesday %>
        </div>
        </td>
        <td class="text-center">
          <div class="field">
          <%= form.label 'Wednesday' %>
          <br>
          <%= form.check_box :wednesday, id: :event_wednesday %>
        </div>
        </td>
        <td class="text-center">
          <div class="field">
          <%= form.label 'Thursday' %>
          <br>
          <%= form.check_box :thursday, id: :event_thursday %>
        </div>
        </td>
        <td class="text-center">
          <div class="field">
          <%= form.label 'Friday' %>
          <br>
          <%= form.check_box :friday, id: :event_friday %>
        </div>
        </td>
        <td class="text-center">
          <div class="field">
          <%= form.label 'Saturday' %>
          <br>
          <%= form.check_box :saturday, id: :event_saturday %>
        </div>
        </td>
      </tr>
    </tbody>
  </table>

  <br>

  <%= form.label 'What are your preferred times?' %>
  <div class="container">
    <div class="field">
      <%= form.label 'No earlier than' %>
      <br>
      <%= form.time_select :start_time, id: :event_start_time, minute_step: 15, ampm: true %>
    </div>
    <br>
    <div class="field">
      <%= form.label 'No later than' %>
      <br>
      <%= form.time_select :end_time, id: :event_end_time, minute_step: 15, ampm: true %>
    </div>
  </div>

  <br>

  <div class="field">
    <%= form.label 'Enter an email to invite the user.' %>
    <%= form.text_field @email, id: :event_location, class: 'form-control' %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<br>

<div class="actions">
  <%= link_to 'Back', events_path, class: 'btn btn-primary' %>
</div>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table class="table table-light">
  <thead>
    <tr>
      <th class="table-dark bg-primary">Title</th>
      <th class="table-dark bg-primary">Location</th>
      <th class="table-dark bg-primary">Start Time</th>
      <th class="table-dark bg-primary">End Time</th>
      <th class="table-dark bg-primary" colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.location %></td>
        <td><%= event.start_time %></td>
        <td><%= event.end_time %></td>
        <td><%= link_to 'View Availabilities', view_event_path(event) %></td>
        <td><%= link_to 'Select Availabilities', select_event_path(event) %></td>
        <td><%= link_to 'Edit Event/Invite People', edit_event_path(event) %></td>
        <td><%= link_to 'Delete Event', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>


</table>

<br>


<div class="actions">
  <%= link_to 'Create a New Event', new_event_path, class: 'btn btn-primary' %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<br>

<div class="actions">
  <%= link_to 'Back', events_path, class: 'btn btn-primary' %>
</div>

app/views/events/select.html.erb
<p id="notice">
  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>
</p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<% row_count = (@event.end_time.hour - @event.start_time.hour) * 4 %>
<% col_count = @event.end_time.mday - @event.start_time.mday + 1 %>
<% row = 0 %>
<% col = 0 %>
<% timeslots = [] %>

<table>
  <thead>
  </thead>
</table>

<div class="container">
  <% while row < row_count %>
    <div class="row border">
      <% while col < col_count %>
        <div class="col border">
         <%= slot = DateTime.new(@event.start_time.year, @event.start_time.month, @event.start_time.mday + col, @event.start_time.hour + (row / 4), @event.start_time.min + 15 * (row  % 4)) %>
        </div>
        <% col += 1 %>
      <% end %>
    </div>
    <% row += 1 %>
  <% end %>
</div>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<% row_count = (@event.end_time.hour - @event.start_time.hour) * 4 %>
<% col_count = @event.end_time.mday - @event.start_time.mday + 1 %>
<% row = 0 %>
<% col = 0 %>
<% timeslots = [] %>

<div class="container">
  <% while row <= row_count %>
    <div class="row">
      <% while col <= col_count %>
        <div class="col">
          <%= slot = DateTime.new(@event.end_time.year, @event.end_time.month, @event.end_time.mday + col, @event.end_time.hour + (row / 4), @event.end_time.minute + (row % 4) %>
          <div class="actions">
          </div>
        </div>
      <% col_count = col_count + 1 %>
      <% end %>
    </div>
  <% row_count = row_count + 1 %>
  <% end %>
</div>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/events/view.html.erb
<p id="notice">
  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>
</p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<% row_count = (@event.end_time.hour - @event.start_time.hour) * 4 %>
<% col_count = @event.end_time.mday - @event.start_time.mday + 1 %>
<% row = 0 %>
<% col = 0 %>
<% timeslots = [] %>

<div class="container">
  <% while row < row_count %>
    <div class="row border">
      <% while col < col_count %>
        <div class="col border">
         <%= slot = DateTime.new(@event.start_time.year, @event.start_time.month, @event.start_time.mday + col, @event.start_time.hour + (row / 4), @event.start_time.min + 15 * (row  % 4)) %>
        </div>
        <% col += 1 %>
      <% end %>
    </div>
    <% row += 1 %>
  <% end %>
</div>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4">
  <div class="container">
    <%= link_to 'When2Meet 2.0', root_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><%= link_to 'Events', events_path, class: 'nav-link' %></li>

        <% if logged_in? %>
          <%# Only display the current user's name, friend requests and log out links if a user is logged in %>
          <li class="nav-item"><%= link_to 'Account Settings', edit_user_path(current_user), class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Log out', '/logout', method: :delete, class: 'nav-link' %></li>
        <% else %>
          <%# Only display the sign up and log in links if no user is logged in %>
          <li class="nav-item"><%= link_to 'Sign up', new_user_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Log in', '/login', class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>When2Meet 2.0</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.email_field :email, id: :user_email, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :password%>
    <%= form.password_field :password, id: :user_password, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Account Settings</h1>

<p id="notice">
  <% if notice %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>
</p>

<%= render 'form', user: @user %>

<br>

<div class="actions">
  <%= link_to 'Back', events_path, class: 'btn btn-primary' %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<% if logged_in? %>
  <div class="row">
    <div class="col-lg-6 offset-lg-3">

    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-lg-6 offset-lg-3">
      <% if @events.blank? %>
        <p class="text-center">You don't have any events.</p>
      <% else %>
        <% @events.each do |status| %>
          <%= render 'events/event', event: event %>
          <br>
        <% end %>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-lg-6 offset-lg-3">
      <h1>Welcome to When2Meet 2.0!</h1>
      <p>To get started, sign up with a new account or log in with a current one!</p>
    </div>
  </div>
<% end %>